### PR TITLE
linting actions added

### PR DESCRIPTION
**Pull request by ahmetcihank**
in terms of #32 linting actions  are added in pr&release steps

### CODE REVIEW

**Comment by ahmetcihank** [comment]
apologies there is a mistake , i am gonna re open.

**Comment by ahmetcihank** [comment]
I did some refactoring in order to fix linting issues, however i can revert @aliok

**Comment by aliok** [comment]
@ahmetcihank looks great!

The linter action is complaining though 😄 , which shows it is working fine, though need to fix the linting issues

**Comment by aliok** [comment]
/lgtm
/approve

Great job, thanks @ahmetcihank

**Comment by aliok** [comment]
Fixes #32

**Review by aliok — APPROVED** [review]

**Pull request merged**
