### PR TITLE
Slack notification will be sent when NPM publish process finished

### LINKED ISSUE #14: NPM publish process should send a Slack notification
Context:
- https://github.com/knative-extensions/backstage-plugins/pull/13#discussion_r1439255984
- How: https://github.com/knative/release/blob/main/.github/workflows/releasability.yaml#L125

### PR DESCRIPTION
**Pull request by Leo6Leo**
Fixes #14 
# Changes

- Slack notification will be sent when NPM publish process finished
- Adding the Fail if No-Go

**Release Note**

```release-note
Slack notification will be sent when NPM publish process finished
```

May need help on setting the environment variables.

/cc @aliok @dsimansk

### CODE REVIEW

**Comment by dsimansk** [comment]
> /hold unhold until the environmental variables are being set and the workflow works properly.

If this is only about `SLACK_WEBHOOK`. It's org wide env var, no worries.

**Comment by aliok** [comment]
@Leo6Leo were you able to verify on Slack that this works?

**Pull request merged**
